### ISSUE TITLE
Provide help string for arguments

### ISSUE THREAD

**Issue by speidy** [p-ranav/structopt#17]
Hello,

I would like to add some help strings for the arguments / subcommands defined in the options struct.

i.e. - provide an explanation for what each subcommand does or for the arguments in the help usage.

Is it currently possible?

Thanks for the great work!

**Comment by p-ranav** [comment]
It is not currently possible but it is definitely the most high priority feature I'm trying to implement. I don't yet have a clean interface for the user to be able to provide this help description per argument (keeping in mind that this needs to work for nested structs).

**Comment by speidy** [comment]
It might be passed to STRUCTOPT macro as an optional argument

**Comment by p-ranav** [comment]
In the latest version, this should now be possible. See [here](https://github.com/p-ranav/structopt#printing-custom-help). You can provide custom help messages to `structopt::app`. Thanks for the request.
