### ISSUE TITLE
Custom help message

### ISSUE THREAD

**Issue by kamchatka-volcano** [p-ranav/structopt#19]
Hi, do you plan to add ability of setting up a custom help message? structopt adds --help command line flag unconditionally, without ability to override built-in help message format, so I think it makes sense even if you add a help description per argument in the future.
It requires only a small change, I made it to the structopt bundled in my project, you can see how it looks [here](https://github.com/kamchatka-volcano/lunchtoast/blob/master/src/main.cpp#L62-L80)

**Comment by p-ranav** [comment]
Thanks for the request. 

Yeah it makes sense to support this - optionally disabling or overriding the default generated help message. My only concern is probably if there are any implications to nested structs (subcommands) but this can be given a little thought and then solved I'm sure.
