### ISSUE TITLE
config file vs args

### ISSUE THREAD

**Issue by juliangaal** [p-ranav/structopt#7]
The examples don't make clear, if all arguments can be passed from within a config file imho. Can this be done?

**Comment by p-ranav** [comment]
`structopt` is a command-line argument parser. The library does not open or parse configuration files for you. You can certainly pass the config file name as an argument but you will need to open/parse the config files, e.g., JSON, XML etc., yourself.

**Comment by juliangaal** [comment]
ok, thanks!
